// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Security.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Security token identifier
type TokenProto struct {
	Identifier           []byte   `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	Password             []byte   `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	Kind                 *string  `protobuf:"bytes,3,req,name=kind" json:"kind,omitempty"`
	Service              *string  `protobuf:"bytes,4,req,name=service" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenProto) Reset()         { *m = TokenProto{} }
func (m *TokenProto) String() string { return proto.CompactTextString(m) }
func (*TokenProto) ProtoMessage()    {}
func (*TokenProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e9851c4f1a8f1de, []int{0}
}

func (m *TokenProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenProto.Unmarshal(m, b)
}
func (m *TokenProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenProto.Marshal(b, m, deterministic)
}
func (m *TokenProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenProto.Merge(m, src)
}
func (m *TokenProto) XXX_Size() int {
	return xxx_messageInfo_TokenProto.Size(m)
}
func (m *TokenProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenProto.DiscardUnknown(m)
}

var xxx_messageInfo_TokenProto proto.InternalMessageInfo

func (m *TokenProto) GetIdentifier() []byte {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *TokenProto) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *TokenProto) GetKind() string {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return ""
}

func (m *TokenProto) GetService() string {
	if m != nil && m.Service != nil {
		return *m.Service
	}
	return ""
}

type CredentialsKVProto struct {
	Alias                *string     `protobuf:"bytes,1,req,name=alias" json:"alias,omitempty"`
	Token                *TokenProto `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Secret               []byte      `protobuf:"bytes,3,opt,name=secret" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CredentialsKVProto) Reset()         { *m = CredentialsKVProto{} }
func (m *CredentialsKVProto) String() string { return proto.CompactTextString(m) }
func (*CredentialsKVProto) ProtoMessage()    {}
func (*CredentialsKVProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e9851c4f1a8f1de, []int{1}
}

func (m *CredentialsKVProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialsKVProto.Unmarshal(m, b)
}
func (m *CredentialsKVProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialsKVProto.Marshal(b, m, deterministic)
}
func (m *CredentialsKVProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialsKVProto.Merge(m, src)
}
func (m *CredentialsKVProto) XXX_Size() int {
	return xxx_messageInfo_CredentialsKVProto.Size(m)
}
func (m *CredentialsKVProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialsKVProto.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialsKVProto proto.InternalMessageInfo

func (m *CredentialsKVProto) GetAlias() string {
	if m != nil && m.Alias != nil {
		return *m.Alias
	}
	return ""
}

func (m *CredentialsKVProto) GetToken() *TokenProto {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *CredentialsKVProto) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

type CredentialsProto struct {
	Tokens               []*CredentialsKVProto `protobuf:"bytes,1,rep,name=tokens" json:"tokens,omitempty"`
	Secrets              []*CredentialsKVProto `protobuf:"bytes,2,rep,name=secrets" json:"secrets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CredentialsProto) Reset()         { *m = CredentialsProto{} }
func (m *CredentialsProto) String() string { return proto.CompactTextString(m) }
func (*CredentialsProto) ProtoMessage()    {}
func (*CredentialsProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e9851c4f1a8f1de, []int{2}
}

func (m *CredentialsProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialsProto.Unmarshal(m, b)
}
func (m *CredentialsProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialsProto.Marshal(b, m, deterministic)
}
func (m *CredentialsProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialsProto.Merge(m, src)
}
func (m *CredentialsProto) XXX_Size() int {
	return xxx_messageInfo_CredentialsProto.Size(m)
}
func (m *CredentialsProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialsProto.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialsProto proto.InternalMessageInfo

func (m *CredentialsProto) GetTokens() []*CredentialsKVProto {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *CredentialsProto) GetSecrets() []*CredentialsKVProto {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type GetDelegationTokenRequestProto struct {
	Renewer              *string  `protobuf:"bytes,1,req,name=renewer" json:"renewer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDelegationTokenRequestProto) Reset()         { *m = GetDelegationTokenRequestProto{} }
func (m *GetDelegationTokenRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetDelegationTokenRequestProto) ProtoMessage()    {}
func (*GetDelegationTokenRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e9851c4f1a8f1de, []int{3}
}

func (m *GetDelegationTokenRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDelegationTokenRequestProto.Unmarshal(m, b)
}
func (m *GetDelegationTokenRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDelegationTokenRequestProto.Marshal(b, m, deterministic)
}
func (m *GetDelegationTokenRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDelegationTokenRequestProto.Merge(m, src)
}
func (m *GetDelegationTokenRequestProto) XXX_Size() int {
	return xxx_messageInfo_GetDelegationTokenRequestProto.Size(m)
}
func (m *GetDelegationTokenRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDelegationTokenRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetDelegationTokenRequestProto proto.InternalMessageInfo

func (m *GetDelegationTokenRequestProto) GetRenewer() string {
	if m != nil && m.Renewer != nil {
		return *m.Renewer
	}
	return ""
}

type GetDelegationTokenResponseProto struct {
	Token                *TokenProto `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetDelegationTokenResponseProto) Reset()         { *m = GetDelegationTokenResponseProto{} }
func (m *GetDelegationTokenResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetDelegationTokenResponseProto) ProtoMessage()    {}
func (*GetDelegationTokenResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e9851c4f1a8f1de, []int{4}
}

func (m *GetDelegationTokenResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDelegationTokenResponseProto.Unmarshal(m, b)
}
func (m *GetDelegationTokenResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDelegationTokenResponseProto.Marshal(b, m, deterministic)
}
func (m *GetDelegationTokenResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDelegationTokenResponseProto.Merge(m, src)
}
func (m *GetDelegationTokenResponseProto) XXX_Size() int {
	return xxx_messageInfo_GetDelegationTokenResponseProto.Size(m)
}
func (m *GetDelegationTokenResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDelegationTokenResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_GetDelegationTokenResponseProto proto.InternalMessageInfo

func (m *GetDelegationTokenResponseProto) GetToken() *TokenProto {
	if m != nil {
		return m.Token
	}
	return nil
}

type RenewDelegationTokenRequestProto struct {
	Token                *TokenProto `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RenewDelegationTokenRequestProto) Reset()         { *m = RenewDelegationTokenRequestProto{} }
func (m *RenewDelegationTokenRequestProto) String() string { return proto.CompactTextString(m) }
func (*RenewDelegationTokenRequestProto) ProtoMessage()    {}
func (*RenewDelegationTokenRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e9851c4f1a8f1de, []int{5}
}

func (m *RenewDelegationTokenRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewDelegationTokenRequestProto.Unmarshal(m, b)
}
func (m *RenewDelegationTokenRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewDelegationTokenRequestProto.Marshal(b, m, deterministic)
}
func (m *RenewDelegationTokenRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewDelegationTokenRequestProto.Merge(m, src)
}
func (m *RenewDelegationTokenRequestProto) XXX_Size() int {
	return xxx_messageInfo_RenewDelegationTokenRequestProto.Size(m)
}
func (m *RenewDelegationTokenRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewDelegationTokenRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_RenewDelegationTokenRequestProto proto.InternalMessageInfo

func (m *RenewDelegationTokenRequestProto) GetToken() *TokenProto {
	if m != nil {
		return m.Token
	}
	return nil
}

type RenewDelegationTokenResponseProto struct {
	NewExpiryTime        *uint64  `protobuf:"varint,1,req,name=newExpiryTime" json:"newExpiryTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenewDelegationTokenResponseProto) Reset()         { *m = RenewDelegationTokenResponseProto{} }
func (m *RenewDelegationTokenResponseProto) String() string { return proto.CompactTextString(m) }
func (*RenewDelegationTokenResponseProto) ProtoMessage()    {}
func (*RenewDelegationTokenResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e9851c4f1a8f1de, []int{6}
}

func (m *RenewDelegationTokenResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewDelegationTokenResponseProto.Unmarshal(m, b)
}
func (m *RenewDelegationTokenResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewDelegationTokenResponseProto.Marshal(b, m, deterministic)
}
func (m *RenewDelegationTokenResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewDelegationTokenResponseProto.Merge(m, src)
}
func (m *RenewDelegationTokenResponseProto) XXX_Size() int {
	return xxx_messageInfo_RenewDelegationTokenResponseProto.Size(m)
}
func (m *RenewDelegationTokenResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewDelegationTokenResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_RenewDelegationTokenResponseProto proto.InternalMessageInfo

func (m *RenewDelegationTokenResponseProto) GetNewExpiryTime() uint64 {
	if m != nil && m.NewExpiryTime != nil {
		return *m.NewExpiryTime
	}
	return 0
}

type CancelDelegationTokenRequestProto struct {
	Token                *TokenProto `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CancelDelegationTokenRequestProto) Reset()         { *m = CancelDelegationTokenRequestProto{} }
func (m *CancelDelegationTokenRequestProto) String() string { return proto.CompactTextString(m) }
func (*CancelDelegationTokenRequestProto) ProtoMessage()    {}
func (*CancelDelegationTokenRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e9851c4f1a8f1de, []int{7}
}

func (m *CancelDelegationTokenRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelDelegationTokenRequestProto.Unmarshal(m, b)
}
func (m *CancelDelegationTokenRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelDelegationTokenRequestProto.Marshal(b, m, deterministic)
}
func (m *CancelDelegationTokenRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelDelegationTokenRequestProto.Merge(m, src)
}
func (m *CancelDelegationTokenRequestProto) XXX_Size() int {
	return xxx_messageInfo_CancelDelegationTokenRequestProto.Size(m)
}
func (m *CancelDelegationTokenRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelDelegationTokenRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_CancelDelegationTokenRequestProto proto.InternalMessageInfo

func (m *CancelDelegationTokenRequestProto) GetToken() *TokenProto {
	if m != nil {
		return m.Token
	}
	return nil
}

type CancelDelegationTokenResponseProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelDelegationTokenResponseProto) Reset()         { *m = CancelDelegationTokenResponseProto{} }
func (m *CancelDelegationTokenResponseProto) String() string { return proto.CompactTextString(m) }
func (*CancelDelegationTokenResponseProto) ProtoMessage()    {}
func (*CancelDelegationTokenResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e9851c4f1a8f1de, []int{8}
}

func (m *CancelDelegationTokenResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelDelegationTokenResponseProto.Unmarshal(m, b)
}
func (m *CancelDelegationTokenResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelDelegationTokenResponseProto.Marshal(b, m, deterministic)
}
func (m *CancelDelegationTokenResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelDelegationTokenResponseProto.Merge(m, src)
}
func (m *CancelDelegationTokenResponseProto) XXX_Size() int {
	return xxx_messageInfo_CancelDelegationTokenResponseProto.Size(m)
}
func (m *CancelDelegationTokenResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelDelegationTokenResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_CancelDelegationTokenResponseProto proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TokenProto)(nil), "hadoop.common.TokenProto")
	proto.RegisterType((*CredentialsKVProto)(nil), "hadoop.common.CredentialsKVProto")
	proto.RegisterType((*CredentialsProto)(nil), "hadoop.common.CredentialsProto")
	proto.RegisterType((*GetDelegationTokenRequestProto)(nil), "hadoop.common.GetDelegationTokenRequestProto")
	proto.RegisterType((*GetDelegationTokenResponseProto)(nil), "hadoop.common.GetDelegationTokenResponseProto")
	proto.RegisterType((*RenewDelegationTokenRequestProto)(nil), "hadoop.common.RenewDelegationTokenRequestProto")
	proto.RegisterType((*RenewDelegationTokenResponseProto)(nil), "hadoop.common.RenewDelegationTokenResponseProto")
	proto.RegisterType((*CancelDelegationTokenRequestProto)(nil), "hadoop.common.CancelDelegationTokenRequestProto")
	proto.RegisterType((*CancelDelegationTokenResponseProto)(nil), "hadoop.common.CancelDelegationTokenResponseProto")
}

func init() { proto.RegisterFile("Security.proto", fileDescriptor_0e9851c4f1a8f1de) }

var fileDescriptor_0e9851c4f1a8f1de = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0xe5, 0xb4, 0xdb, 0xe8, 0xdb, 0x86, 0x90, 0x85, 0x90, 0xe1, 0x30, 0x52, 0x6b, 0x87,
	0x70, 0x20, 0x91, 0x76, 0x03, 0x6e, 0x1b, 0x08, 0x21, 0x2e, 0xc8, 0xab, 0x38, 0x70, 0x33, 0xc9,
	0x23, 0xb5, 0x9a, 0xda, 0xc1, 0x76, 0x5b, 0xca, 0x5f, 0x80, 0xf8, 0x2b, 0xf8, 0x53, 0x51, 0x9c,
	0xa6, 0xa4, 0x50, 0x50, 0x0f, 0xdc, 0xfa, 0x3d, 0xf7, 0xfb, 0x7d, 0xdf, 0x73, 0x64, 0xb8, 0x7b,
	0x8b, 0xf9, 0xc2, 0x2a, 0xbf, 0x4e, 0x6b, 0x6b, 0xbc, 0xa1, 0xe7, 0x53, 0x59, 0x18, 0x53, 0xa7,
	0xb9, 0x99, 0xcf, 0x8d, 0xe6, 0x4b, 0x80, 0x89, 0x99, 0xa1, 0x7e, 0x17, 0x0e, 0x2f, 0x00, 0x54,
	0x81, 0xda, 0xab, 0x4f, 0x0a, 0x2d, 0x23, 0x71, 0x94, 0x9c, 0x89, 0xde, 0x84, 0x3e, 0x82, 0x3b,
	0xb5, 0x74, 0x6e, 0x65, 0x6c, 0xc1, 0xa2, 0x70, 0xba, 0xd5, 0x94, 0xc2, 0x70, 0xa6, 0x74, 0xc1,
	0x06, 0x71, 0x94, 0x8c, 0x44, 0xf8, 0x4d, 0x19, 0x9c, 0x38, 0xb4, 0x4b, 0x95, 0x23, 0x1b, 0x86,
	0x71, 0x27, 0xb9, 0x03, 0x7a, 0x63, 0x31, 0x90, 0x65, 0xe5, 0xde, 0xbe, 0x6f, 0xf3, 0xef, 0xc3,
	0x91, 0xac, 0x94, 0x74, 0x21, 0x7a, 0x24, 0x5a, 0x41, 0x33, 0x38, 0xf2, 0x4d, 0x47, 0x16, 0xc5,
	0x24, 0x39, 0xbd, 0x7a, 0x98, 0xee, 0xac, 0x90, 0xfe, 0xea, 0x2f, 0xda, 0xff, 0xd1, 0x07, 0x70,
	0xec, 0x30, 0xb7, 0xe8, 0xd9, 0x20, 0x26, 0xc9, 0x99, 0xd8, 0x28, 0xfe, 0x9d, 0xc0, 0xbd, 0x5e,
	0x6a, 0x9b, 0xf9, 0x0c, 0x8e, 0x83, 0xab, 0x09, 0x1d, 0x24, 0xa7, 0x57, 0xe3, 0xdf, 0xf0, 0x7f,
	0xd6, 0x14, 0x1b, 0x03, 0x7d, 0xd1, 0xac, 0xd7, 0x90, 0x1d, 0x8b, 0x0e, 0xf5, 0x76, 0x0e, 0xfe,
	0x1c, 0x2e, 0x5e, 0xa3, 0x7f, 0x89, 0x15, 0x96, 0xd2, 0x2b, 0xa3, 0xc3, 0x1a, 0x02, 0x3f, 0x2f,
	0xd0, 0xf9, 0xb6, 0x19, 0x83, 0x13, 0x8b, 0x1a, 0x57, 0x9b, 0x4f, 0x31, 0x12, 0x9d, 0xe4, 0x02,
	0x1e, 0xef, 0xf3, 0xba, 0xda, 0x68, 0x87, 0xad, 0x79, 0x7b, 0x69, 0xe4, 0xb0, 0x4b, 0xe3, 0xb7,
	0x10, 0x8b, 0x06, 0xff, 0xaf, 0x46, 0x3d, 0x68, 0x74, 0x10, 0xf4, 0x0d, 0x8c, 0xf7, 0x43, 0xfb,
	0x55, 0x2f, 0xe1, 0x5c, 0xe3, 0xea, 0xd5, 0x97, 0x5a, 0xd9, 0xf5, 0x44, 0xcd, 0x31, 0xd0, 0x87,
	0x62, 0x77, 0xc8, 0x27, 0x30, 0xbe, 0x91, 0x3a, 0xc7, 0xea, 0xbf, 0x16, 0xbc, 0x04, 0xfe, 0x17,
	0x6a, 0xaf, 0xe1, 0x75, 0x0e, 0xb1, 0xb1, 0x65, 0x2a, 0x6b, 0x99, 0x4f, 0xb1, 0x63, 0xba, 0x9d,
	0x87, 0x75, 0xbd, 0x7d, 0x68, 0xc1, 0xe2, 0x3e, 0x3c, 0x29, 0x95, 0x9f, 0x2e, 0x3e, 0x36, 0xd1,
	0x19, 0x56, 0x38, 0xcb, 0xcc, 0x57, 0xa3, 0xf1, 0x69, 0x69, 0x32, 0x59, 0xab, 0x2c, 0x78, 0xb2,
	0xb6, 0xd6, 0x37, 0x42, 0x7e, 0x10, 0xf2, 0x33, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x5a, 0xa3, 0xae,
	0xaa, 0x03, 0x00, 0x00,
}
